# 1. Sets

In [1]:
set_1 = {1,2,3,4,"Hola"}


In [3]:
set_1

{1, 2, 3, 4, 'Hola'}

In [5]:
set_1.add(10)
set_1

{1, 10, 2, 3, 4, 'Hola'}

In [6]:
set_1.add(10)
set_1

{1, 10, 2, 3, 4, 'Hola'}

### es el comportaiento de la union

In [8]:
set1 = {1,2,3,4,5}
set2 = {5,6,7,8,9,4}

In [9]:
set1.union(set2) # set2.union(set2)

{1, 2, 3, 4, 5, 6, 7, 8, 9}

In [10]:
set1.intersection(set2)

{4, 5}

In [11]:
set1.difference(set2)

{1, 2, 3}

In [13]:
set2.difference(set1)

{6, 7, 8, 9}

In [14]:
set1.symmetric_difference(set2)# comparar dos conjuntos de datos en función del tiempo

{1, 2, 3, 6, 7, 8, 9}

In [15]:
letras = {"abc", "dfg", "hij"}
letras

{'abc', 'dfg', 'hij'}

In [16]:
mayusculas = {l.upper() for l in letras}
mayusculas

{'ABC', 'DFG', 'HIJ'}

# 2. Numpy

In [17]:
import numpy as np # los datos se guardan de forma secuencial en la memoria

In [18]:
x = [1,2,3,4,5]
x

[1, 2, 3, 4, 5]

In [19]:
x1 = np.array(x,dtype = 'float')
x1

array([1., 2., 3., 4., 5.])

In [20]:
np.arange(1,11,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
np.linspace(1,5,10) # retorna un arreglo con un paso constante, el necesario para crear 10 numeros

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [22]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [26]:
np.zeros_like(x)

array([0, 0, 0, 0, 0])

# 2.1 Rangos y Dimensiones

In [31]:
x = np.zeros([10,10])

In [32]:
#dimensiones del tensor.
x.shape # cantidad de elementos que tiene cada dimensión

(10, 10)

In [34]:
#rango del tensor
x.ndim

2

In [33]:
x[2,1]

0.0

In [36]:
x = np.array([[[10, 20, 30, 40, 50], 
               [60, 70, 80, 90, 100]], 
               [[100, 200, 300, 400, 500], 
                [600, 700, 800, 900, 1000]]
            ])

In [37]:
x.shape

(2, 2, 5)

In [38]:
x.ndim

3

In [39]:
x[0][1][3]

90

In [40]:
x[1,1,4]

1000

# 2.2 - Operaciones con Vectores

In [43]:
v = np.arange(1,6,1)
w = np.arange(6,11,1)

In [48]:
print(v)

[1 2 3 4 5]


In [44]:
print(v + w)
print(v - w)
print(v * w)
print(v / w)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [45]:
#Broadcasting
v*2

array([ 2,  4,  6,  8, 10])

In [46]:
print(v/2)
print(v + 5)
print( v - 10)
print(v % 2)

[0.5 1.  1.5 2.  2.5]
[ 6  7  8  9 10]
[-9 -8 -7 -6 -5]
[1 0 1 0 1]


In [ ]:
#en listas normales en Python, so se puede hacer broadcasting
x = [1,2,3]
x + 2

# 2.4 -Funciones Universales

In [49]:
x= np.array([-2,-1,0,1,1,3,6])
x

array([-2, -1,  0,  1,  1,  3,  6])

In [51]:
print(np.sign(x))
print(np.abs(x))
print(np.cos(x)) 
print(np.sin(x))
print(np.exp(x))
print(np.log(x))
print(np.sqrt(x))

[-1 -1  0  1  1  1  1]
[2 1 0 1 1 3 6]
[-0.41614684  0.54030231  1.          0.54030231  0.54030231 -0.9899925
  0.96017029]
[-0.90929743 -0.84147098  0.          0.84147098  0.84147098  0.14112001
 -0.2794155 ]
[1.35335283e-01 3.67879441e-01 1.00000000e+00 2.71828183e+00
 2.71828183e+00 2.00855369e+01 4.03428793e+02]
[       nan        nan       -inf 0.         0.         1.09861229
 1.79175947]
[       nan        nan 0.         1.         1.         1.73205081
 2.44948974]


C:\Users\paco\AppData\Local\Temp\ipykernel_1188\2365994234.py:6: RuntimeWarning: divide by zero encountered in log
  print(np.log(x))
C:\Users\paco\AppData\Local\Temp\ipykernel_1188\2365994234.py:6: RuntimeWarning: invalid value encountered in log
  print(np.log(x))
C:\Users\paco\AppData\Local\Temp\ipykernel_1188\2365994234.py:7: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(x))


In [52]:
x = np.array([1,2,3,4,5,6,7,8,9,2,2])
x_nan = np.array([1,2,3,4, np.nan, 6, 8, 10, np.nan])

In [ ]:
np.mean(x)

In [ ]:
np.nanmean(x_nan)

In [56]:
print(np.max(x))
print(np.nanmax(x))


9
9


In [57]:
print(np.min(x))
print(np.nanmin(x_nan))

1
1.0


In [58]:
print(np.var(x))
print(np.nanvar(x_nan))

6.793388429752068
9.26530612244898


In [59]:
print(np.prod(x))
print(np.nanprod(x_nan))

1451520
11520.0


In [ ]:
print(np.argmax(x))# posición del valor más pequeño  proyecto
print(np.nanargmax(x_nan))